Repository Turing-MOD4-Cross-Pollination/front-end-help-yourself, pull requests merged in 2019-12, with the labels that each got.

#5 React-native initial file setup
  .expo-shared/assets.json
  .gitignore
  App.js
  app.json
  assets/icon.png
  assets/splash.png
  babel.config.js
  communityconnect/.gitignore
  package-lock.json
  package.json
Labels: FE, MVP, Phase 1

#7 React Native navigation initial setup
  App.js
  HomeScreen.js
  package-lock.json
  package.json
Labels: FE, MVP, Phase 1

#8 Add Home screen buttons and styling
  App.js
  ForMeScreen.js
  HomeScreen.js
  NearMeScreen.js
  NowScreen.js
Labels: FE, MVP, Phase 1, enhancement

#9 Add links to components convert class components to functional
  ForMeScreen.js
  HomeScreen.js
  NearMeScreen.js
  NowScreen.js
Labels: FE, MVP, Phase 1

#14 Accordion menu on ForMe page
  components/Chevron.jsx
  components/ForMeList.jsx
  components/ForMeListItem.jsx
  components/ForMeScreen.jsx
  package-lock.json
  package.json
  util/categories.js
Labels: FE, MVP
