Repository Turing-MOD4-Cross-Pollination/front-end-help-yourself, pull requests merged in 2020-01, with the labels that each got.

#18 App and Home Components
  .gitignore
  App.js
  Home.js
  actions/index.js
  assets/splash.old.png
  assets/splash.png
  components/ForMeList.jsx
  package-lock.json
  package.json
  reducers/allResources.js
  reducers/index.js
  reducers/selectedResources.js
  util/apiCalls.js
Labels: FE, MVP

#20 Style HomeScreen component to look like Sketch wireframe spec
  Home.js
  assets/logo.png
  components/HomeScreen.js
Labels: FE, MVP, Phase 1, enhancement

#23 Add geolocation map and react-maps package to Near Me section
  components/HomeScreen/HomeScreen.js
  components/NearMeScreen/NearMeScreen.js
  package-lock.json
  package.json
Labels: FE, MVP, Phase 1, enhancement

#24 Add styling for multiple devices
  components/ForMeScreen/ForMeScreen.js
  components/HomeScreen/HomeScreen.js
Labels: FE

#27 Fetch data into Redux store, dial numbers on-screen automatically and add test map markers
  Home.js
  README.md
  actions/index.js
  components/Chevron.js
  components/Footer/Footer.js
  components/ForMeScreen/ForMeList.js
  components/ForMeScreen/ForMeListItem.js
  components/ForMeScreen/ForMeScreen.js
  components/HomeScreen/HomeScreen.js
  components/NearMeScreen/NearMeScreen.js
  components/NowScreen/EmergencyItem.js
  components/NowScreen/NowScreen.js
  package-lock.json
  package.json
  reducers/allCategories.js
  reducers/index.js
  reducers/selectedCategories.js
  reducers/selectedResources.js
  util/apiCalls.js
  util/categories.js
Labels: FE, MVP, enhancement, phase 3

#28 Implements redux-persist
  App.js
  package-lock.json
  package.json
  store.js
Labels: MVP

#32 Adds poetic to project and lints components
  .editorconfig
  .eslintignore
  .eslintrc.js
  .prettierrc.js
  .vscode/settings.json
  App.js
  Home.js
  actions/actions.test.js
  actions/index.js
  components/Footer/Footer.test.js
  components/ForMeScreen/ForMeList.js
  components/ForMeScreen/ForMeListItem.js
  components/ForMeScreen/ForMeScreen.js
  components/HomeScreen/HomeScreen.js
  components/HomeScreen/HomeScreen.test.js
  components/NearMeScreen/NearMeScreen.js
  components/NowScreen/EmergencyItem.js
  components/NowScreen/NowScreen.js
  package-lock.json
  package.json
  reducers/allResources.js
  reducers/reducers.test.js
  reducers/select.js
  reducers/selectedCategories.js
  store.js
  tsconfig.json
  util/apiCalls.js
  yarn.lock
Labels: FE, MVP, enhancement, phase 3

#33 Adds Poetic to project
  components/ForMeScreen/ForMeScreen.js
  components/ForMeScreen/ResourceItem.js
  components/HomeScreen/HomeScreen.js
  components/NearMeScreen/NearMeScreen.js
  components/NowScreen/EmergencyItem.js
  components/NowScreen/NowScreen.js
Labels: FE, enhancement, phase 3

#34 Optimize components, re-lint and refine styling
  .vscode/settings.json
  Home.js
  components/Chevron.js
  components/Footer/Footer.js
  components/Footer/Footer.test.js
  components/Footer/__snapshots__/Footer.test.js.snap
  components/ForMeScreen/ForMeList.js
  components/ForMeScreen/ForMeListItem.js
  components/ForMeScreen/ForMeScreen.js
  components/ForMeScreen/Resource.js
  components/ForMeScreen/ResourceItem.js
  components/HomeScreen/HomeScreen.js
  components/NearMeScreen/NearMeScreen.js
  components/NowScreen/EmergencyItem.js
  components/NowScreen/NowScreen.js
  data/resources.js
Labels: FE, MVP, enhancement, phase 3

#35 Testing react native
  components/ForMeScreen/ForMeScreen.test.js
  components/HomeScreen/HomeScreen.test.js
  components/HomeScreen/__snapshots__/HomeScreen.test.js.snap
  components/NearMeScreen/NearMeScreen.js
  components/NearMeScreen/NearMeScreen.test.js
  components/NearMeScreen/__snapshots__/NearMeScreen.test.js.snap
  package-lock.json
  package.json
Labels: FE, MVP, phase 3

#36 Initialize fetch and redux for recovery meetings
  Home.js
  actions/index.js
  reducers/allMeetings.js
  reducers/index.js
  util/apiCalls.js
Labels: FE, enhancement

#37 Testing for new Recovery redux
  components/HomeScreen/__snapshots__/HomeScreen.test.js.snap
  components/NearMeScreen/__snapshots__/NearMeScreen.test.js.snap
  reducers/allMeetings.js
  reducers/allResources.js
  reducers/reducers.test.js
Labels: FE, MVP, bug, enhancement

#39 Fix Redux data bug
  Home.js
Labels: FE, MVP, bug

#40 Fetch and add map markers to map
  Home.js
  components/NearMeScreen/NearMeScreen.js
  util/apiCalls.js
Labels: FE, MVP, enhancement, phase 3
